### PR TITLE
Adding bluebird promises

### PR DESCRIPTION
**Pull request by jdalrymple**
Added the bluebird library to handle the promise functionality instead of the default node promise library. The default library is missing some the recent functionality. It would be nice to put it in as a option for those using the library and i don't mind changing it to work as such, but this was the quickest way to add the missing functionality.

### CODE REVIEW

**Comment by jdalrymple** [comment]
This is a pretty noob question, but how can i test the changes. I attempted to do npm test, but got  a "const is a reserved word" error. :s

EDIT* Realised this has to do with the es6 syntax i was using. Do we want to update the node versions this is applicable for? Or should i revert those changes to make it backwards compatible ? @alykoshin

**Comment by alykoshin** [comment]
hi, @jdalrymple 
sorry for the delay. now I'm back.

as of the tests (https://travis-ci.org/alykoshin/nssm/jobs/180481731), they fail with 'SyntaxError: Use of const in strict mode.' for 0.12 (this is because of ES6 var&const). 
I think, we may remove tests for 0.12 (it is configured in travis.ci in root dir) - the oldest version I need to support is 4.2.6 which looks ok with var&const.

but for other Node versions (>=4.0)it fails with 'Cannot find module 'Mockery'' as module name starts with lowercase letter in require() (test/index.js, line 7 https://github.com/jdalrymple/nssm/blob/master/test/index.js#L7)....


ADD:
Also, I consider Expect, Mockery etc as functions, not constructors... what is the reason to write their names with capital letter? Lowercase is also used in Chai's docs: http://chaijs.com/

**Comment by jdalrymple** [comment]
Welcome back! I'll look into that last test over the next few days!



via Newton Mail [https://cloudmagic.com/k/d/mailapp?ct=pa&cv=9.3.19&pv=6.0.1&source=email_footer_2] On Thu, Dec 08, 2016 at 5:18pm, Alexander < notifications@github.com [notifications@github.com] > wrote:
hi, @jdalrymple [https://github.com/jdalrymple]
sorry for the delay. now I'm back.

as of the tests ( https://travis-ci.org/alykoshin/nssm/jobs/180481731 [https://travis-ci.org/alykoshin/nssm/jobs/180481731] ), they fail with 'SyntaxError: Use of const in strict mode.' for 0.12 (this is because of ES6 var&const).
I think, we may remove tests for 0.12 (it is configured in travis.ci in root dir) - the oldest version I need to support is 4.2.6 which looks ok with var&const.

but for other Node versions (>=4.0)it fails with 'Cannot find module 'Mockery'' as module name starts with lowercase letter in require() (test/index.js, line 7 https://github.com/jdalrymple/nssm/blob/master/test/index.js#L7 [https://github.com/jdalrymple/nssm/blob/master/test/index.js#L7] )....

**Comment by jdalrymple** [comment]
Fixed the code that was failing the tests and cleaned up the tests a bit. The two travis tests that are failing run in node v<4.0.0. The first one is node 0.12.0 and the io.js one is running on node v3.3.1. Io.js has been merged back into the nodejs branch since 4.0.0 :) https://iojs.org/en/

**Pull request closed without merging**
